export { LoginPage } from './LoginPage';
export { DashboardPage } from './DashboardPage';
export { StudentsPage } from './StudentsPage';
export { StudentDetailPage } from './StudentDetailPage';
export { ProgramsPage } from './ProgramsPage';
export { AttendancePage } from './AttendancePage';
export { AnalyticsPage } from './AnalyticsPage';
export { ReportsPage } from './ReportsPage';
export { SettingsPage } from './SettingsPage';
